services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce-mds-net


  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - ecommerce-mds-net


  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10

    networks:
      - ecommerce-mds-net


  connect:
    image: debezium/connect:2.2

    depends_on:
      - kafka
      - zookeeper
      - postgres

    ports:
      - "8083:8083"

    environment:
      BOOTSTRAP_SERVERS: kafka:9092

      GROUP_ID: 1

      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      KEY_CONVERTER_SCHEMAS_ENABLE: false
      VALUE_CONVERTER_SCHEMAS_ENABLE: false

    networks:
      - ecommerce-mds-net


  minio:
    image: minio/minio:latest

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - ./docker/minio/data:/data

    networks:
      - ecommerce-mds-net


  airflow-postgres:
    image: postgres:15

    container_name: airflow-postgres

    restart: always

    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}

    ports:
      - "5433:5432"

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${AIRFLOW_DB_USER}",
          "-d",
          "${AIRFLOW_DB_NAME}"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - ecommerce-mds-net


  airflow-init:

    build:
      context: .
      dockerfile: dockerfile-airflow.dockerfile

    container_name: airflow-init

    entrypoint: /bin/bash

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB_NAME}

      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./docker/dags:/opt/airflow/dags
      - ./docker/logs:/opt/airflow/logs
      - ./docker/plugins:/opt/airflow/plugins
      - ./ecommerce_dbt:/opt/airflow/ecommerce_dbt
      - ./ecommerce_dbt/.dbt:/home/airflow/.dbt

    command: >
      -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      --password ${AIRFLOW_ADMIN_PASSWORD:-admin}
      "

    networks:
      - ecommerce-mds-net


  airflow-scheduler:

    build:
      context: .
      dockerfile: dockerfile-airflow.dockerfile

    container_name: airflow-scheduler

    restart: always

    depends_on:
      airflow-postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB_NAME}

      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./docker/dags:/opt/airflow/dags
      - ./docker/logs:/opt/airflow/logs
      - ./docker/plugins:/opt/airflow/plugins
      - ./ecommerce_dbt:/opt/airflow/ecommerce_dbt
      - ./ecommerce_dbt/.dbt:/home/airflow/.dbt

    command: scheduler

    networks:
      - ecommerce-mds-net


  airflow-webserver:

    build:
      context: .
      dockerfile: dockerfile-airflow.dockerfile

    container_name: airflow-webserver

    restart: always

    depends_on:
      airflow-postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

      airflow-scheduler:
        condition: service_started

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB_NAME}

      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}

    volumes:
      - ./docker/dags:/opt/airflow/dags
      - ./docker/logs:/opt/airflow/logs
      - ./docker/plugins:/opt/airflow/plugins
      - ./ecommerce_dbt:/opt/airflow/ecommerce_dbt
      - ./ecommerce_dbt/.dbt:/home/airflow/.dbt

    ports:
      - "8080:8080"

    command: webserver

    networks:
      - ecommerce-mds-net


volumes:
  airflow_postgres_data:


networks:
  ecommerce-mds-net:
    name: ecommerce-mds-net